############################################################
# Dockerfile for Sane-stack to run sails.js API application
############################################################

FROM node

MAINTAINER Markus Padourek <markus@artificial.io>

RUN apt-get update && \
	apt-get install -y	git \
						vim \
						zsh \
						sqlite3 \
						build-essential \
						libssl-dev

RUN npm install -g sails grunt bower pm2 npm-check-updates
RUN echo 'if [ -d /root/Server ]; then cd /root/Server; fi' >> ~/.bashrc

# Expose ports.
EXPOSE 1337
